# Workflow to run the scripts automatically in June 
name: Dublin Airport Queues in June

on:
  schedule:
   - cron: '0/15 * * 6 *'  # Every 15 mins in June
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Github Checkout
        uses: actions/checkout@v3

      - name: Setup python enviroment
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Build dependencies and run the script 
        run: |
          pip install -r requirements.txt
          python main.py
          
      - name: Save the data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Extended data [bot]
          file_pattern: data/*.csv
