# Workflow to run the scripts automatically in June 
name: Dublin Airport Queues in June

on:
  schedule:
    - cron: '0/10 * 6 * *'  # Every 10 mins in June
  
  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Github Checkout
        uses: actions/checkout@v3

      - run: ls -a

      - name: Uncaching previous data
        uses: actions/cache@v3
        with:
          path: data
          key: previous-data

    - run: ls -a

      - name: Setup python enviroment
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Download dependencies and run the script 
        run: |
          pip install -r requirements.txt
          python main.py
          
      - name: Save the data
        uses: actions/upload-artifact@v3
        with:
          name: The queue times
          path: data/*.csv
          
